version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./container/flask/Dockerfile
    container_name: 'flask-app-docker'
    volumes:
      - .:/app
    ports:
      - "8080:8080"

